server:
  port: 8076

spring:
  application:
    name: service-transrecord
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://127.0.0.1:3306/bsbank?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver  # If anything wrong, delete the "cj".

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


